### ISSUE TITLE
Create the repo in the fullstack org

### ISSUE THREAD

**Issue by EliasSalom** [YouKnowWho24/myCvRsume#1]
hu Fida, 
I have been asking to open this repo in the Fullstack alfanar organization, 
**but I found now that you have been open here on your GitHub account** 
please do the task requirement by

- [x] move this repo to the fullstack organization
- [x] remove update me here
- [x] close this issue

**Comment by FidaKhoury** [comment]
the repo is removed to the fullstack organization
